### ISSUE TITLE
Support multiple values for a property in the table

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#123]
Currently, the table only shows one value even if there are multiple.

**Comment by esjewett** [comment]
@alexsherman I'd suggest this is something you could pick up. The specific problem is that the table only shows one value for a property even if multiple values exist. I would suggest that you approach this as follows, but feel free to do it differently:

 - Create a new component for display of a table cell that is bound to a `IPropertyToValues`
 - Use that component in `explore-table-component.pug` around line 20 instead of `{{e.values[0].label.value}}` - it would bind to `e`, which should be of the expected type
 - Handle all the different situations in the component:
   - Literal value
   - Multiple literal values
   - Entity (initially just display the value the same as we are currently, but eventually we will want to display an appropriate label somehow)
   - Multiple Entity values
