### ISSUE TITLE
Create project on local hits wrong endpoint URL

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#186]
hits fibra/sparql instead of fibra/update even if /fibra/update is maintained as the UPDATE URL.

**Comment by jiemakel** [comment]
Gah. The problem is that the project != the project definition, and I'm allowing for separate endpoints only on the project. To fix storing project info on a local Fuseki I'll have to start passing on the update and graph store endpoint information on the definition objects themselves. I'll think through if I want to do this, or actually just go through with copying the schemas and configs on project initialization, which would lessen the need for separate endpoint tracking quite a bit.

**Comment by jiemakel** [comment]
Should now be fixed.
