### ISSUE TITLE
ReferenceError issue when loading build, items not displaying

### ISSUE THREAD

**Issue by alexsherman** [humanitiesplusdesign/fibra#2]
After syncing with the most recent changes and running npm install, I'm getting the following error message: 

![fibra issue1](https://cloud.githubusercontent.com/assets/5248189/16739832/dded0974-4750-11e6-970f-11d8f6291660.png)

None of the previous items are showing up in the table or the explore tab for me right now.

**Comment by esjewett** [comment]
@alexsherman I ran into this yesterday and just forgot to push the fix. Can you pull the latest and try again?

**Comment by alexsherman** [comment]
Yes, that fixed it. Thanks!

**Comment by jiemakel** [comment]
Hmm. I moved us to ES6 on purpose because it has a couple of features I wanted to use, and didn't have problems with my browsers, but now reading up on it more thoroughly, it does seem that we would rule out just too wide a collection of browsers by adopting it. 

I guess I'll just have to do without my candy.

**Comment by esjewett** [comment]
Yeah, it seemed to break in both Safari and Chrome for me.

I think there are polyfills for most features. What did you have in mind? http://babeljs.io/docs/usage/polyfill/ may be worth a look.

**Comment by jiemakel** [comment]
I was looking into polyfills also just now, but think they may not be worth it due to their inner complexity. TypeScript already supports a lot of the ES6 syntax features even on ES5 targets, and while I initially thought I'd like the proper Map and Set implementations, turns out that I actually hate them because 1) the keys are compared using identity comparisons and 2) the ES6 version of an Iterable is something horrible :).

**Comment by jiemakel** [comment]
I was looking into polyfills also just now, but think they may not be worth it due to their inner complexity. TypeScript already supports a lot of the ES6 syntax features even on ES5 targets, and while I initially thought I'd like the proper Map and Set implementations, turns out that I actually hate them because 1) the keys are compared using identity comparisons and 2) the ES6 version of an Iterable is something horrible :).

**Comment by esjewett** [comment]
Ok, sounds fair. Symbols though... :-)

I think we can use d3.map for Map-like behavior. Not sure if it meets your standards, but it's a lot better than using JS object properties.
