### ISSUE TITLE
Click to add notice does not disappear. And what is drag mode?

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#50]
![screen shot 2016-12-06 at 1 52 43 pm](https://cloud.githubusercontent.com/assets/288005/20945422/125ebea2-bbbc-11e6-8fdd-b77bf009ab83.png)

**Comment by esjewett** [comment]
Draw mode is where you click and drag to link nodes together. The thing with the label sticking happened to me once too, but having a hard time recreating it. I think it has to do with a label being displayed during during an update. Let's leave this issue here to track it.

My theory: When you click on the sunburst to add nodes, there is a delay before the nodes show up. If a label is displayed at the moment the new nodes appear, the label sticks like this.

**Comment by esjewett** [comment]
I should also note that draw mode does not, at the moment, create a link that has any permanence. In fact, it disappears when you add new nodes. We need to get these user-created links persisted on the application state, allow users to label them, etc.

**Comment by cncoleman** [comment]
How about if we just silence draw mode. I'd like to know what triggers it. When are we *not* in draw mode?

**Comment by alexsherman** [comment]
Draw mode can be toggled in and out of with shift currently.

**Comment by esjewett** [comment]
Ok, I think this is actually a consistent issue with the label from the sunburst itself. Need to hide it when the user clicks? I will take care of it.
